version: '3.8'

services:
  server:
    image: myimage/tests:latest
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    ports:
      - "8000:8000"

  tests:
    build:
      context: .
      dockerfile: docker/tests/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    volumes:
      - .:/opt/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
      - blacklist_tests

  blacklist_tests:
    build:
      context: .
      dockerfile: docker/blacklist_tests/Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env.example
    volumes:
      - .:/opt/app
    environment:
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

volumes:
  postgres_data: